name: Docker Image CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Descargar el código del repositorio

    - name: Log in to Docker Hub  # Iniciar sesión en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Usar secrets para credenciales
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the Docker image  # Construir la imagen de Docker desde la carpeta correcta
      run: docker build ./ --file ./Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/foodhub-backend

    - name: Push Docker image  # Subir la imagen a Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/foodhub-backend
